export default {
  arrowBackBlack: require('images/arrowBackBlack.png'),
  heartMediumPurple: require('images/heartMediumPurple.png'),
  logoSmall: require('images/logoSmall.png'),
  addUserWhite: require('images/addUserWhite.png'),
  logoBig: require('images/logoBig.png'),
  notificationsImg: require('images/notificationsImg.png'),
  editSmallPurple: require('images/editSmallPurple.png'),
  exampleAvatar: require('images/exampleAvatar.png'),
  howToPlay: require('images/howToPlay.png'),
  submitTrivia: require('images/submitTrivia.png'),
  getHelp: require('images/getHelp.png'),
  rateUs: require('images/rateUs.png'),
  twitter: require('images/twitter.png'),
  instagram: require('images/instagram.png'),
  facebook: require('images/facebook.png'),
  extraLive: require('images/extraLive.png'),
  flagRus: require('images/flagRus.png'),
  arrowBackWhite: require('images/arrowBackWhite.png'),
  crossWhite: require('images/crossWhite.png'),
  crossBlack: require('images/crossBlack.png'),
}